Repository wri/gfw-mapbuilder, pull requests merged in 2020-04, with the labels that each got.

#935 Ticket 931 - toggle bugfix
  src/js/components/leftPanel/layersPanel/LayerToggleSwitch.tsx
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#936 Ticket 915 - DateRange.tsx style
  src/css/index.scss
  src/css/leftpanel.scss
  src/js/components/leftPanel/layersPanel/DateRange.tsx
Labels: 4.x Upgrade

#932 Ticket 716 - WEBMAP_GROUP content
  package-lock.json
  src/js/components/sharedComponents/InfoContent.tsx
Labels: 4.x Upgrade

#933 styling and UI elements for analysis tab
  src/css/leftpanel.scss
  src/images/chart-icon.svg
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/leftPanel/analysisPanel/analysisTranslations.ts
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#938 Ticket 870 - doc tab UI
  configs/leftPanel.config.ts
  src/css/leftpanel.scss
  src/js/components/leftPanel/DocumentsTabView.tsx
Labels: 4.x Upgrade

#941 Ticket 858 - myGFW dropdown closes onClick
  src/js/components/header/GFWLogin.tsx
  src/js/components/header/Header.tsx
  src/js/components/leftPanel/LeftPanel.tsx
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/legend/Legend.tsx
  src/js/controllers/mapController.ts
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
Labels: 4.x Upgrade

#940 Layer Loading and language changing logic rework
  configs/cameroon.js
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/legend/generateLegendItems.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/LayerFactory.ts
  src/js/helpers/mapController/Documents.ts
  src/js/helpers/mapController/miscLayerHelpers.ts
  src/js/helpers/shareFunctionality.ts
  src/js/interfaces/mapping.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#950 Ticket 778 - Print widget UI
  configs/modal.config.ts
  src/css/index.scss
  src/css/modalCard.scss
  src/js/components/mapWidgets/widgetContent/printContent.tsx
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#949 Ticket 927 - Search quick UI
  src/js/components/mapWidgets/widgetContent/searchContent.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/mapController/searchSources.ts
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
Labels: 4.x Upgrade

#952 Analysis tab control - vega charts
  .eslintrc.js
  package-lock.json
  package.json
  src/css/leftpanel.scss
  src/js/components/header/GFWLogin.tsx
  src/js/components/header/Header.tsx
  src/js/components/leftPanel/LeftPanel.tsx
  src/js/components/leftPanel/analysisPanel/AnalysisTabView.tsx
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/leftPanel/analysisPanel/InputComponents.tsx
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/sharedComponents/CanopyDensityPicker.tsx
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
Labels: 4.x Upgrade

#948 Bugfix - Sketch widget
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/controllers/mapController.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#964 Ticket 843 - header URL
  src/js/store/appSettings/reducers.ts
Labels: 4.x Upgrade

#961 Report
  custom.d.ts
  package-lock.json
  package.json
  src/css/leftpanel.scss
  src/css/modalCard.scss
  src/css/printButton.scss
  src/css/report.scss
  src/images/downloadIcon.svg
  src/images/gearIcon.svg
  src/js/components/App.tsx
  src/js/components/DatePicker.tsx
  src/js/components/MapContent.tsx
  src/js/components/Report.tsx
  src/js/components/ReportChartsComponent.tsx
  src/js/components/ReportRangeSlider.tsx
  src/js/components/ReportTable.tsx
  src/js/components/ReportUtils.ts
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/leftPanel/analysisPanel/VegaChartContainer.tsx
  src/js/components/leftPanel/analysisPanel/VegaChartCreator.tsx
  src/js/components/leftPanel/dataPanel/DataTabFooter.tsx
  src/js/components/mapWidgets/widgetContent/shareContent.tsx
  src/js/components/sharedComponents/DownloadOptions.tsx
  src/js/components/sharedComponents/Loader.tsx
  src/js/components/sharedComponents/PrintReportButton.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/MapGraphics.ts
  src/js/helpers/dataPanel/DataPanel.ts
  src/js/helpers/dataPanel/getAttributes.ts
  src/js/helpers/shareFunctionality.ts
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
  src/js/store/mapview/actions.ts
  src/js/store/mapview/reducers.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade, high priority

#965 Report folder structure change
  src/js/components/Report.tsx
  src/js/components/report/DatePicker.tsx
  src/js/components/report/ReportChartsComponent.tsx
  src/js/components/report/ReportRangeSlider.tsx
  src/js/components/report/ReportTable.tsx
  src/js/components/report/ReportUtils.ts
Labels: 4.x Upgrade

#967 Add MASK layer config loading
  src/js/controllers/mapController.ts
  src/js/helpers/LayerFactory.ts
  src/js/helpers/dataPanel/DataPanel.ts
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#970 Layer Controls Language
  configs/countryConfigs/cameroon.js
  configs/countryConfigs/central-african-republic.js
  configs/countryConfigs/democratic-republic-congo.js
  configs/countryConfigs/equatorial-guinea.js
  configs/countryConfigs/ethiopia.js
  configs/countryConfigs/gabon-parks.js
  configs/countryConfigs/gabon.js
  configs/countryConfigs/georgia.js
  configs/countryConfigs/india-sidi.js
  configs/countryConfigs/india.js
  configs/countryConfigs/kenya.js
  configs/countryConfigs/liberia.js
  configs/countryConfigs/paraguay.js
  configs/countryConfigs/republic-of-congo.js
  configs/leftPanel.translations.ts
  src/css/leftpanel.scss
  src/js/components/App.tsx
  src/js/components/leftPanel/DocumentsTabView.tsx
  src/js/components/leftPanel/analysisPanel/AnalysisTabView.tsx
  src/js/components/leftPanel/layersPanel/BasemapLayersGroup.tsx
  src/js/components/leftPanel/layersPanel/LayersTabView.tsx
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#971 Layer factory in extraLayers
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#973 960 layer panel structure
  configs/countryConfigs/cameroon.js
  src/css/leftpanel.scss
  src/js/components/leftPanel/layersPanel/DefaultLayerGroup.tsx
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/leftPanel/layersPanel/LayerRadioButton.tsx
  src/js/components/leftPanel/layersPanel/WebmapLayersGroup.tsx
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#976 Adding nested layer group support
  configs/countryConfigs/cameroon.js
  src/css/leftpanel.scss
  src/js/components/leftPanel/layersPanel/DefaultLayerGroup.tsx
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#978 Adding a timeout logic for legend info
  src/js/controllers/mapController.ts
  src/js/helpers/legendInfo.ts
Labels: 4.x Upgrade, bug

#980 Adding layer filtering logic
  configs/countryConfigs/cameroon.js
  package-lock.json
  package.json
  src/css/leftpanel.scss
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/legend/generateLegendItems.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/legendInfo.ts
  src/js/helpers/mapController/miscLayerHelpers.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade, bug

#979 Ticket 710 - font files
  src/css/variables.scss
  src/fonts/firasans-bold-webfont.ttf
  src/fonts/firasans-bold-webfont.woff
  src/fonts/firasans-bold-webfont.woff2
  src/fonts/firasans-light-webfont.ttf
  src/fonts/firasans-light-webfont.woff
  src/fonts/firasans-light-webfont.woff2
  src/fonts/firasans-regular-webfont.ttf
  src/fonts/firasans-regular-webfont.woff
  src/fonts/firasans-regular-webfont.woff2
Labels: 4.x Upgrade

#977 Ticket 835 - template literal
  configs/leftPanel.translations.ts
  src/js/components/leftPanel/analysisPanel/AnalysisTabView.tsx
Labels: 4.x Upgrade

#975 Ticket 953 - edit/save/delete buttons - UI
  src/css/leftpanel.scss
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/leftPanel/analysisPanel/analysisTranslations.ts
Labels: 4.x Upgrade

#982 Title and subtitle language/config awareness
  src/js/components/header/Header.tsx
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#986 Conditional recent imagery loading based on config
  src/js/components/leftPanel/layersPanel/LayersTabView.tsx
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#987 Open header links in new tab based on config
  src/js/components/header/Header.tsx
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#985 hideFooter and hideHeader implementation for conditional render
  src/js/components/App.tsx
  src/js/components/MapContent.tsx
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#988 Filter layers based on config
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#990 Ticket 984 - Narrative tab styling
  package-lock.json
  src/css/leftpanel.scss
Labels: 4.x Upgrade

#989 Ticket 968 - language dropdown
  src/css/header.scss
  src/images/infoBoxIcon.svg
  src/js/components/header/Header.tsx
  src/js/components/header/LanguageDropdown.tsx
Labels: 4.x Upgrade

#993 Report crash bug fix - graphics layers
  src/js/helpers/MapGraphics.ts
  src/js/helpers/generateSymbol.ts
Labels: 4.x Upgrade, bug

#992 Layer versioning support
  configs/countryConfigs/cameroon.js
  src/css/leftpanel.scss
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/leftPanel/layersPanel/LayerVersionPicker.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/LayerFactory.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#994 889 feature server layer legends
  configs/countryConfigs/cameroon.js
  src/js/components/leftPanel/layersPanel/LayerVersionPicker.tsx
  src/js/components/legend/Legend.tsx
  src/js/components/legend/generateLegendItems.tsx
  src/js/controllers/mapController.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#995 Initial extent sync
  .eslintrc.js
  configs/countryConfigs/cameroon.js
  src/js/controllers/mapController.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#996 Webmap group name based on the config
  src/js/components/leftPanel/layersPanel/WebmapLayersGroup.tsx
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#997 APP ID awareness
  src/js/components/App.tsx
  src/js/components/legend/generateLegendItems.tsx
  src/js/components/mapWidgets/widgetContent/shareContent.tsx
  src/js/components/sharedComponents/PrintReportButton.tsx
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#1001 Theme picker
  configs/countryConfigs/cameroon.js
  src/css/header.scss
  src/images/themesIcon.svg
  src/js/components/App.tsx
  src/js/components/header/Header.tsx
  src/js/components/header/LanguageDropdown.tsx
  src/js/components/header/ThemeDropdown.tsx
  src/js/components/header/header.translations.ts
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#1003 Ticket 999 - legend max-height
  src/css/legend.scss
Labels: 4.x Upgrade

#1004 Ticket 1000 - fonts audit
  src/css/header.scss
  src/css/leftpanel.scss
  src/css/legend.scss
  src/css/measureContent.scss
  src/css/modalCard.scss
  src/css/penContent.scss
  src/css/uploadFile.scss
Labels: 4.x Upgrade
