Repository wri/gfw-mapbuilder, pull requests merged in 2020-02, with the labels that each got.

#744 Added unused country configurations
  configs/central-african-republic.js
  configs/democratic-republic-congo.js
  configs/equatorial-guinea.js
  configs/ethiopia.js
  configs/gabon-parks.js
  configs/gabon.js
  configs/georgia.js
  configs/india-sidi.js
  configs/india.js
  configs/kenya.js
  configs/liberia.js
  configs/paraguay.js
  configs/republic-of-congo.js
Labels: 4.x Upgrade, Exemplar, quick PR

#745 Layer groups logic changes
  src/js/components/leftPanel/layersPanel/DefaultLayerGroup.tsx
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/leftPanel/layersPanel/LCLayersGroup.tsx
  src/js/components/leftPanel/layersPanel/LayerTransparencySlider.tsx
  src/js/components/leftPanel/layersPanel/LayersTabView.tsx
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#746 All available layers additions
  package-lock.json
  src/js/components/leftPanel/layersPanel/DefaultLayerGroup.tsx
  src/js/components/leftPanel/layersPanel/WebmapLayersGroup.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/layer-utils.js
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#748 Capitalization for TS compilation
  src/js/components/leftPanel/layersPanel/LayersTabView.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesDMSSection.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesForm.tsx
Labels: 4.x Upgrade, high priority, quick PR

#750 Consistent casing rule addition
  tsconfig.json
Labels: 4.x Upgrade, typescript

#757 removing esri default zoom widget from the map
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#756 Remove Measure Tab from Left Panel
  src/images/measurementTabIcon.svg
  src/js/components/leftPanel/LeftPanel.tsx
  src/js/components/leftPanel/MeasurementTabView.tsx
  src/js/components/leftPanel/TabViewContainer.tsx
Labels: 4.x Upgrade

#759 Ticket 724 - Share widget logic
  src/css/modalCard.scss
  src/images/facebookIcon.svg
  src/images/twitterIcon.svg
  src/js/components/mapWidgets/widgetContent/shareContent.tsx
  src/js/components/modal/modalCard.tsx
Labels: 4.x Upgrade

#752 Resource layers to map
  src/css/leftpanel.scss
  src/js/controllers/mapController.ts
  src/js/helpers/LayerFactory.ts
  src/js/helpers/layer-utils.js
  src/js/interfaces/mapping.ts
  src/js/layers/TreeCoverGainLayer.ts
  src/js/layers/TreeCoverLossLayer.ts
Labels: 4.x Upgrade

#758 Ticket 720 - Print widget logic
  configs/modal.config.ts
  src/css/modalCard.scss
  src/js/components/mapWidgets/widgetContent/printContent.tsx
  src/js/components/modal/modalCard.tsx
  src/js/controllers/mapController.ts
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#766 Lint update
  .eslintrc.js
  src/js/components/Hello.tsx
Labels: 4.x Upgrade

#767 Controlled the Header & conditional LangDrop from Redux
  src/js/components/header/Header.tsx
  src/js/components/header/LanguageDropdown.tsx
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade, quick PR

#773 Allowed layer types sync
  configs/layer-config.ts
  package.json
  src/js/components/mapWidgets/widgetContent/shareContent.tsx
  tests/__mocks__/class.js
  tests/__mocks__/constructor.js
  tests/__mocks__/object.js
  tests/layerFactory.test.js
Labels: 4.x Upgrade

#775 Lang switch ts - Create new webmap on language-toggle
  src/js/components/header/LanguageDropdown.tsx
  src/js/controllers/mapController.ts
  src/js/store/appState/actions.ts
Labels: 4.x Upgrade

#784 Tickets 769 & 770 - area logic
  src/js/components/mapWidgets/widgetContent/measureContent.tsx
  src/js/controllers/mapController.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
Labels: 4.x Upgrade

#747 Ticket 749 - Measurement widget
  .eslintrc.js
  configs/modal.config.ts
  src/css/measureContent.scss
  src/js/components/mapWidgets/widgetContent/measureContent.tsx
  src/js/controllers/mapController.ts
  src/js/interfaces/measureWidget.ts
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
Labels: 4.x Upgrade

#795 Ticket 760 - change onBlur() to onChange()
  src/js/components/mapWidgets/widgetContent/coordinatesDMSSection.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesForm.tsx
  src/js/components/mapWidgets/widgetContent/measureContent.tsx
  src/js/components/mapWidgets/widgetContent/printContent.tsx
Labels: bug

#794 Data tab data fetching and basic UI implementation
  src/css/index.scss
  src/css/leftpanel.scss
  src/images/analysisPolyIcon.svg
  src/js/components/leftPanel/DataTabView.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/DataPanel.ts
  src/js/store/mapview/actions.ts
  src/js/store/mapview/reducers.ts
  src/js/store/mapview/types.ts
  tsconfig.json
Labels: 4.x Upgrade

#796 Ticket 722 - Search widget logic
  configs/modal.config.ts
  src/css/modalCard.scss
  src/js/components/mapWidgets/widgetContent/searchContent.tsx
  src/js/components/modal/modalCard.tsx
  src/js/controllers/mapController.ts
  src/js/store/appState/actions.ts
Labels: 4.x Upgrade

#801 Ticket 799 - pen widget logic - draw polygon via user input form
  src/js/components/mapWidgets/widgetContent/coordinatesForm.tsx
  src/js/controllers/mapController.ts
  src/js/utils/helper.config.ts
Labels: 4.x Upgrade

#810 Visibility Toggle Fix #809
  src/js/components/leftPanel/LeftPanel.tsx
Labels: 4.x Upgrade, bug

#807 Ticket 806 - pen widget - user input form
  src/js/components/mapWidgets/widgetContent/coordinatesDMSSection.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesForm.tsx
  src/js/controllers/mapController.ts
  src/js/interfaces/coordinateForm.ts
  src/js/utils/helper.config.ts
Labels: 4.x Upgrade

#813 Ticket 788 - Constants in Measure widget
  src/js/components/mapWidgets/widgetContent/measureContent.tsx
Labels: 4.x Upgrade

#804 Ticket 802 - coordinateform.tsx - DD UI
  src/css/coordinatesForm.scss
  src/js/components/mapWidgets/widgetContent/coordinatesDDSection.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesDMSSection.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesForm.tsx
  src/js/interfaces/coordinateForm.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#822 Ticket 818 - onShare, update URL to include X/Y/Z coordinates and visibleLayer IDs
  src/js/components/mapWidgets/widgetContent/shareContent.tsx
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#805 Data Tab UI Implementation (pt 1)
  src/css/leftpanel.scss
  src/images/down-arrow.png
  src/js/components/leftPanel/DataTabView.tsx
  src/js/components/leftPanel/TabViewContainer.tsx
  src/js/components/leftPanel/dataPanel/DataTabFooter.tsx
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/components/leftPanel/dataPanel/DefaultTabView.tsx
  src/js/components/leftPanel/dataPanel/LayerSelector.tsx
  src/js/components/leftPanel/layersPanel/LayersTabView.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/DataPanel.ts
Labels: 4.x Upgrade

#821 Request geometry buffering
  src/js/helpers/DataPanel.ts
Labels: 4.x Upgrade, bug

#826 Ticket 825 - Left panel - Info tab
  src/css/leftpanel.scss
  src/js/components/leftPanel/InfoTabView.tsx
  src/js/components/leftPanel/LeftPanel.tsx
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#820 Ticket 803 - coordinateForm.tsx - DD logic
  src/js/components/mapWidgets/widgetContent/coordinatesForm.tsx
  src/js/controllers/mapController.ts
  src/js/utils/helper.config.ts
Labels: 4.x Upgrade

#832 Data tab remove attribute functionality
  src/css/leftpanel.scss
  src/images/closeIcon.svg
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/controllers/mapController.ts
  src/js/store/mapview/actions.ts
  src/js/store/mapview/reducers.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#842 Ticket 833 - Mapbuilder footer
  src/css/footer.scss
  src/js/components/Footer.tsx
  src/js/components/MapContent.tsx
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#836 Ticket 830 - Left Panel, analysis tab UI & logic
  configs/leftPanel.config.ts
  src/css/index.scss
  src/css/leftpanel.scss
  src/css/modalCard.scss
  src/js/components/leftPanel/AnalysisTabView.tsx
Labels: 4.x Upgrade

#846 Ticket 845 - GFW default basemaps
  configs/leftPanel.config.ts
  src/css/leftpanel.scss
  src/js/components/leftPanel/layersPanel/BasemapLayersGroup.tsx
  src/js/controllers/mapController.ts
  src/js/store/mapview/actions.ts
  src/js/store/mapview/reducers.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#850 Ticket 789 - Typesafe this._selectedWidget
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#849 Ticket 848 - Pen widget - Uploading a shapefile logic
  src/js/components/mapWidgets/widgetContent/penContent.tsx
  src/js/components/sharedComponents/UploadFile.tsx
Labels: 4.x Upgrade

#828 Data tab UI table styling
  src/css/leftpanel.scss
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
Labels: 4.x Upgrade

#839 Active Feature highlight on the map
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/MapGraphics.ts
Labels: 4.x Upgrade

#847 Returned feature missing layer info bug
  src/js/helpers/DataPanel.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade, bug

#853 Enabling server side geo returns
  src/js/helpers/DataPanel.ts
  src/js/helpers/MapGraphics.ts
Labels: 4.x Upgrade

#851 Ticket 848 - Uploading a shapefile logic
  configs/modal.config.ts
  src/css/penContent.scss
  src/css/uploadFile.scss
  src/js/components/mapWidgets/widgetContent/penContent.tsx
  src/js/components/sharedComponents/UploadFile.tsx
Labels: 4.x Upgrade

#856 Last feature highlight bug
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/MapGraphics.ts
Labels: 4.x Upgrade, bug

#854 Ticket 848 - Uploading a shapefile UI and logic
  configs/leftPanel.config.ts
  src/css/leftpanel.scss
  src/js/components/leftPanel/AnalysisTabView.tsx
Labels: 4.x Upgrade

#859 Ticket 848 - Uploading a shapefile logic
  src/js/components/sharedComponents/UploadFile.tsx
  src/js/controllers/mapController.ts
  src/js/utils/geojson.config.ts
  src/js/utils/symbol.config.ts
Labels: 4.x Upgrade

#824 Include gfw login
  src/css/modalCard.scss
  src/images/deleteIcon.svg
  src/images/shapeWarning.svg
  src/images/worldShape.svg
  src/js/components/App.tsx
  src/js/components/header/GFWLogin.tsx
  src/js/components/header/Header.tsx
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/mapWidgets/widgetContent/SubscriptionContent.tsx
  src/js/components/mapWidgets/widgetContent/myGFWContent.tsx
  src/js/components/modal/modalCard.tsx
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
  src/js/store/mapview/actions.ts
  src/js/store/mapview/reducers.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade, Code Cleanup

#860 Ticket 848 - Uploading a shapefile UI and logic
  src/css/uploadFile.scss
  src/js/components/sharedComponents/UploadFile.tsx
Labels: 4.x Upgrade

#862 Ticket 861 - MyGFW Subscriptions logic
  src/js/components/mapWidgets/widgetContent/SubscriptionContent.tsx
  src/js/components/mapWidgets/widgetContent/myGFWContent.tsx
  src/js/store/mapview/actions.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade
