Repository wri/gfw-mapbuilder, pull requests merged in 2020-03, with the labels that each got.

#864 Ticket 861 - MyGFW Subscriptions goTo logic
  src/js/components/mapWidgets/widgetContent/SubscriptionContent.tsx
Labels: 4.x Upgrade

#857 WIP - Geostore registration flow
  src/index.html
  src/js/components/leftPanel/AnalysisTabView.tsx
  src/js/components/leftPanel/TabViewContainer.tsx
  src/js/components/leftPanel/analysisPanel/AnalysisTabView.tsx
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/leftPanel/analysisPanel/VegaChartContainer.tsx
  src/js/components/leftPanel/analysisPanel/VegaChartCreator.tsx
  src/js/components/mapWidgets/widgetContent/SubscriptionContent.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesForm.tsx
  src/js/components/sharedComponents/UploadFile.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/DataPanel.ts
  src/js/helpers/coordinatesConversion.ts
  src/js/helpers/generateSymbol.ts
  src/js/helpers/geometryRegistration.ts
  src/js/helpers/spatialDataTransformation.ts
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
  src/js/store/mapview/types.ts
  src/js/utils/geojson.config.ts
  src/library.html
Labels: 4.x Upgrade, Code Cleanup

#866 Ticket 848 - Uploading a shapefile logic
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#868 Ticket 867 - Update FB shareable link
  src/js/components/mapWidgets/widgetContent/shareContent.tsx
Labels: 4.x Upgrade

#872 Type refactor for subscriptions
  src/js/components/mapWidgets/widgetContent/SubscriptionContent.tsx
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#865 Ticket 861 - MyGFW Subscriptions logic
  src/css/modalCard.scss
  src/js/components/mapWidgets/widgetContent/SubscriptionContent.tsx
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#873 Sublayer duplication fix
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/components/leftPanel/dataPanel/LayerSelector.tsx
  src/js/components/leftPanel/layersPanel/ImageryLayersGroup.tsx
  src/js/helpers/DataPanel.ts
Labels: 4.x Upgrade

#874 Ticket 861 - MyGFW Subscriptions UI
  src/css/header.scss
  src/css/variables.scss
  src/images/userIcon.svg
  src/js/components/header/GFWLogin.tsx
  src/js/components/mapWidgets/widgetContent/myGFWContent.tsx
  src/js/components/modal/modalCard.tsx
Labels: 4.x Upgrade

#875 Ticket 716 - Left Panel - Layers Tab
  src/css/leftpanel.scss
  src/css/variables.scss
  src/js/components/leftPanel/analysisPanel/AnalysisTabView.tsx
  src/js/components/leftPanel/dataPanel/DefaultTabView.tsx
  src/js/components/leftPanel/layersPanel/LayerTransparencySlider.tsx
Labels: 4.x Upgrade

#876 Layer Loading Queries
  src/js/components/App.tsx
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/components/leftPanel/dataPanel/LayerSelector.tsx
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/DataPanel.ts
Labels: 4.x Upgrade

#881 Ticket 878 - polygon delete logic
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#879 Tickets 878 & 871 - Polygon CRUD logic & bug fix
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#885 Canopy density control component
  configs/layer-config.ts
  package-lock.json
  package.json
  src/css/canopyDensitymodal.scss
  src/css/leftpanel.scss
  src/images/forest.png
  src/images/tree.png
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/mapWidgets/widgetContent/CanopyDensityContent.tsx
  src/js/components/modal/modalCard.tsx
  src/js/components/sharedComponents/CanopyDensityPicker.tsx
  src/js/controllers/mapController.ts
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
  webpack.common.js
  webpack.lib-production.js
Labels: 4.x Upgrade

#883 Generate Graphic - logic consolidation
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/MapGraphics.ts
Labels: 4.x Upgrade, Code Cleanup

#893 Ticket 891 - rc-slider, LayerTransparencySlider.tsx
  package-lock.json
  src/css/leftpanel.scss
  src/js/components/leftPanel/layersPanel/LayerTransparencySlider.tsx
Labels: 4.x Upgrade

#894 Ticket 892 - Time slider (set-up and styling)
  src/css/leftpanel.scss
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/sharedComponents/TimeSlider.tsx
Labels: 4.x Upgrade

#869 Ticket 848 - Uploading a shapefile logic
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/components/sharedComponents/UploadFile.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/MapGraphics.ts
  src/js/helpers/generateSymbol.ts
  src/js/helpers/geometryRegistration.ts
Labels: 4.x Upgrade

#899 Conditionally hide the coordinate widget button
  src/js/components/mapWidgets/widgetContent/measureContent.tsx
Labels: 4.x Upgrade

#897 ESRI Coordinate widget implementation
  src/css/modalCard.scss
  src/js/components/mapWidgets/widgetContent/measureContent.tsx
  src/js/controllers/mapController.ts
  webpack.common.js
  webpack.lib-production.js
  webpack.production.js
Labels: 4.x Upgrade

#896 WIP - Correct Attribute fetching
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/DataPanel.ts
  src/js/helpers/dataPanel/DataPanel.ts
  src/js/helpers/dataPanel/esriQuery.ts
  src/js/helpers/dataPanel/formatAttributes.ts
  src/js/helpers/dataPanel/getAttributes.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#900 Ticket 892 - TimeSlider logic
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/sharedComponents/TimeSlider.tsx
  src/js/controllers/mapController.ts
  src/js/store/mapview/actions.ts
  src/js/store/mapview/reducers.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#908 Upload file types breaking deploy
  src/js/components/sharedComponents/UploadFile.tsx
Labels: 4.x Upgrade, bug

#909 Ticket 892 - Time slider styling
  src/css/leftpanel.scss
  src/js/components/sharedComponents/TimeSlider.tsx
Labels: 4.x Upgrade

#898 Ticket 870 - Document tab UI & logic
  src/css/leftpanel.scss
  src/images/documentIcon.svg
  src/js/components/leftPanel/DocumentsTabView.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/mapController/Documents.ts
  src/js/interfaces/Attachment.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#911 switch out cameroon basemap for development so basemap is not breaking
  configs/cameroon.js
Labels: 4.x Upgrade

#914 Ticket 798 - Search widget logic
  src/js/controllers/mapController.ts
  src/js/helpers/mapController/searchSources.ts
Labels: 4.x Upgrade

#917 Ticket 915 - Reusable Start/end widget
  src/js/components/leftPanel/layersPanel/DateRange.tsx
  src/js/components/leftPanel/layersPanel/DefaultLayerGroup.tsx
Labels: 4.x Upgrade

#918 Query feature optimization
  src/js/components/legend/Legend.tsx
  src/js/helpers/dataPanel/DataPanel.ts
  src/js/helpers/layerScaleCheck.ts
Labels: 4.x Upgrade, Code Cleanup

#920 Biomass layer support + layer ordering logic
  configs/layer-config.ts
  package-lock.json
  package.json
  src/js/components/mapWidgets/widgetContent/CanopyDensityContent.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/LayerFactory.ts
  src/js/helpers/mapController/layerSorting.ts
  src/js/store/appState/types.ts
Labels: 4.x Upgrade

#919 Ticket 915 - defined date range logic
  configs/modis-viirs.ts
  src/js/components/leftPanel/layersPanel/DateRange.tsx
  src/js/components/leftPanel/layersPanel/DefaultLayerGroup.tsx
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/leftPanel/layersPanel/LayerTransparencySlider.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/MapGraphics.ts
Labels: 4.x Upgrade

#925 Ticket 716 - conditionally returns subtitles
  src/css/leftpanel.scss
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
Labels: 4.x Upgrade

#926 adding webtiled layers to layer factory
  configs/layer-config.ts
  src/js/helpers/LayerFactory.ts
Labels: 4.x Upgrade

#922 Ticket 716 - i button, left panel
  src/css/leftpanel.scss
  src/css/modalCard.scss
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/modal/modalCard.tsx
  src/js/components/sharedComponents/InfoContent.tsx
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
Labels: 4.x Upgrade

#928 Adding download data functionality to layer info panel
  configs/modal.config.ts
  src/css/modalCard.scss
  src/js/components/sharedComponents/InfoContent.tsx
Labels: 4.x Upgrade

#921 Legend gradients support
  src/js/components/legend/LegendLabelComponents.tsx
  src/js/components/legend/generateLegendItems.tsx
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#929 Ticket 915 - date calendar
  src/js/components/leftPanel/layersPanel/DateRange.tsx
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#924 Tree Cover Imagery Layer and Raster Function control
  src/js/components/mapWidgets/widgetContent/CanopyDensityContent.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/LayerFactory.ts
  src/js/interfaces/mapping.ts
Labels: 4.x Upgrade

#930 Share functionality implementation
  src/js/components/App.tsx
  src/js/components/mapWidgets/widgetContent/shareContent.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/shareFunctionality.ts
  src/js/store/mapview/reducers.ts
Labels: 4.x Upgrade
