Repository wri/gfw-mapbuilder, pull requests merged in 2020-01, with the labels that each got.

#699 ESRI Legend widget
  src/js/controllers/mapController.ts
Labels: quick PR

#705 eslint a11y module
  .eslintrc.js
  package-lock.json
  package.json
Labels: quick PR

#717 Ticket 714 - modal content workflow
  configs/modal.config.ts
  src/css/header.scss
  src/css/index.scss
  src/css/modalCard.scss
  src/js/components/App.tsx
  src/js/components/header/LanguageDropdown.tsx
  src/js/components/mapWidgets/mapWidgets.tsx
  src/js/components/mapWidgets/widgetContent/penContent.tsx
  src/js/components/mapWidgets/widgetContent/printContent.tsx
  src/js/components/mapWidgets/widgetContent/searchContent.tsx
  src/js/components/mapWidgets/widgetContent/shareContent.tsx
  src/js/components/modal/modal.config.tsx
  src/js/components/modal/modalCard.tsx
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
Labels: 4.x Upgrade

#719 Upped JS API to 4.14 in dojoConfig
  configs/dojoConfig.ts
Labels: 4.x Upgrade

#718 Redux appstate precision changes
  src/js/components/header/LanguageDropdown.tsx
  src/js/components/mapWidgets/penWidget.tsx
  src/js/components/mapWidgets/printWidget.tsx
  src/js/components/mapWidgets/searchWidget.tsx
  src/js/components/mapWidgets/shareWidget.tsx
  src/js/components/modal/modalCard.tsx
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
Labels: 4.x Upgrade, Exemplar

#723 Ticket 713 - Modal sizing
  src/css/header.scss
  src/css/index.scss
  src/css/mapWidgets.scss
  src/css/modalCard.scss
  src/css/variables.scss
  src/js/components/mapWidgets/mapWidgets.tsx
  src/js/components/modal/modalCard.tsx
Labels: 4.x Upgrade

#727 Leftpanel scaffold - High level implementation
  configs/resources.js
  package-lock.json
  package.json
  src/css/leftpanel.scss
  src/images/analysisTabIcon.svg
  src/images/dataTabIcon.svg
  src/images/documentsTabIcon.svg
  src/images/infoTabIcon.svg
  src/images/layerBaseIcon.svg
  src/images/layersTabIcon.svg
  src/images/measurementTabIcon.svg
  src/js/components/MapContent.tsx
  src/js/components/leftPanel/AnalysisTabView.tsx
  src/js/components/leftPanel/DataTabView.tsx
  src/js/components/leftPanel/DocumentsTabView.tsx
  src/js/components/leftPanel/InfoTabView.tsx
  src/js/components/leftPanel/LayersTabView.tsx
  src/js/components/leftPanel/LeftPanel.tsx
  src/js/components/leftPanel/MeasurementTabView.tsx
  src/js/components/leftPanel/TabViewContainer.tsx
  src/js/store/appSettings/types.ts
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
  tsconfig.json
  webpack.common.js
Labels: 4.x Upgrade

#729 Ticket 721 - Pen tool widget
  package-lock.json
  src/css/modalCard.scss
  src/css/penContent.scss
  src/css/variables.scss
  src/images/plusIcon.svg
  src/images/polygonIcon.svg
  src/js/components/mapWidgets/penWidget.tsx
  src/js/components/mapWidgets/widgetContent/penContent.tsx
  src/js/components/modal/modalCard.tsx
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#731 Test architecture
  .circleci/config.yml
  package-lock.json
  package.json
  tests/resources.test.js
Labels: 4.x Upgrade

#732 Init actions
  .github/workflows/build-and-deploy.yml
  package.json
  src/js/components/leftPanel/LeftPanel.tsx
  src/js/components/mapWidgets/printWidget.tsx
  src/js/components/mapWidgets/shareWidget.tsx
Labels: 4.x Upgrade, dependencies

#733 Ticket 730 - Pen tool - coordinates scaffolding & logic for DMS
  configs/modal.config.ts
  src/css/coordinatesForm.scss
  src/css/variables.scss
  src/js/components/mapWidgets/widgetContent/coordinatesDMSSection.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesForm.tsx
  src/js/components/modal/modalCard.tsx
Labels: 4.x Upgrade

#739 Ticket 738 - Resolve tslint errors (not warnings)
  src/js/components/header/Header.tsx
  src/js/components/header/LanguageDropdown.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesDMSSection.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesForm.tsx
  src/js/components/mapWidgets/widgetContent/penContent.tsx
  src/js/components/modal/modalCard.tsx
Labels: 4.x Upgrade, quick PR

#735 Ticket 725 - Measurement widget
  configs/modal.config.ts
  src/css/measureContent.scss
  src/css/modalCard.scss
  src/css/variables.scss
  src/images/measureIcon.svg
  src/js/components/mapWidgets/mapWidgets.tsx
  src/js/components/mapWidgets/measureWidget.tsx
  src/js/components/mapWidgets/widgetContent/measureContent.tsx
  src/js/components/modal/modalCard.tsx
Labels: 4.x Upgrade

#737 Ticket 736 - Pen widget - add/remove DMS sections
  src/css/coordinatesForm.scss
  src/images/trashCanIcon.svg
  src/js/components/mapWidgets/widgetContent/coordinatesDMSSection.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesForm.tsx
  src/js/components/modal/modalCard.tsx
Labels: 4.x Upgrade

#734 Layers Panel - 716
  package-lock.json
  src/css/index.scss
  src/css/layer-toggle-checkbox.scss
  src/css/leftpanel.scss
  src/images/infoIcon.svg
  src/js/components/leftPanel/LayersTabView.tsx
  src/js/components/leftPanel/TabViewContainer.tsx
  src/js/components/leftPanel/layersPanel/BasemapLayersGroup.tsx
  src/js/components/leftPanel/layersPanel/ExtraLayersGroup.tsx
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/leftPanel/layersPanel/ImageryLayersGroup.tsx
  src/js/components/leftPanel/layersPanel/LCDLayersGroup.tsx
  src/js/components/leftPanel/layersPanel/LCLayersGroup.tsx
  src/js/components/leftPanel/layersPanel/LayerToggleSwitch.tsx
  src/js/components/leftPanel/layersPanel/LayerTransparencySlider.tsx
  src/js/components/leftPanel/layersPanel/LayersTabView.tsx
  src/js/components/leftPanel/layersPanel/WebmapLayersGroup.tsx
  src/js/controllers/mapController.ts
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
  src/js/store/mapview/actions.ts
  src/js/store/mapview/reducers.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade
