Repository wri/gfw-mapbuilder, pull requests merged in 2020-05, with the labels that each got.

#1005 Landsat basemap
  configs/countryConfigs/cameroon.js
  configs/layer-config.ts
  src/css/header.scss
  src/css/leftpanel.scss
  src/js/components/leftPanel/layersPanel/BasemapLayersGroup.tsx
  src/js/controllers/mapController.ts
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#1009 Adding download and about buttons to the header component
  configs/countryConfigs/cameroon.js
  src/css/header.scss
  src/images/aboutIcon.svg
  src/js/components/header/Header.tsx
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#1011 Glad layers controls implementation
  configs/countryConfigs/cameroon.js
  configs/layer-config.ts
  configs/leftPanel.translations.ts
  package-lock.json
  package.json
  src/css/leftpanel.scss
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/legend/Legend.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/LayerFactory.ts
  src/js/layers/GladLayer.ts
Labels: 4.x Upgrade

#1014 glad alert layer start/end dates and confirmed fully share capable
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/helpers/LayerFactory.ts
  src/js/helpers/shareFunctionality.ts
  src/js/layers/GladLayer.ts
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
Labels: 4.x Upgrade

#1016 Terra alerts implementation
  configs/layer-config.ts
  src/css/leftpanel.scss
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/helpers/LayerFactory.ts
  src/js/helpers/shareFunctionality.ts
  src/js/layers/TerraLayer.ts
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
Labels: 4.x Upgrade

#1010 Ticket 861 - myGFW styling
  src/css/header.scss
  src/css/leftpanel.scss
  src/css/modalCard.scss
  src/css/report.scss
  src/css/uploadFile.scss
  src/css/variables.scss
  src/js/components/header/GFWLogin.tsx
  src/js/components/mapWidgets/widgetContent/SubscriptionContent.tsx
  src/js/components/mapWidgets/widgetContent/myGFWContent.tsx
  src/js/components/modal/modalCard.tsx
Labels: 4.x Upgrade

#1017 MODIS and VIIRS Fires alerts improvements
  configs/modis-viirs.ts
  package.json
  src/js/components/leftPanel/layersPanel/DateRangeModisViirs.tsx
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/shareFunctionality.ts
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
  webpack.development.js
Labels: 4.x Upgrade

#1018 Basemap sharing functionality
  configs/countryConfigs/cameroon.js
  src/js/controllers/mapController.ts
  src/js/helpers/shareFunctionality.ts
Labels: 4.x Upgrade

#998 Ticket 984 - Analysis and Doc Tabs "Pulsing" effect
  src/css/leftpanel.scss
  src/js/components/leftPanel/DocumentsTabView.tsx
  src/js/components/leftPanel/LeftPanel.tsx
Labels: 4.x Upgrade

#1019 Adding primary forest layer
  configs/layer-config.ts
  src/js/helpers/LayerFactory.ts
  src/js/layers/PrimaryForestLayer.ts
Labels: 4.x Upgrade

#1022 Custom Color Theme
  package-lock.json
  src/css/leftpanel.scss
  src/images/PolygonIcon.tsx
  src/images/polygonIcon.svg
  src/js/components/leftPanel/DocumentsTabView.tsx
  src/js/components/leftPanel/analysisPanel/AnalysisTabView.tsx
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/leftPanel/analysisPanel/InputComponents.tsx
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/components/leftPanel/dataPanel/DefaultTabView.tsx
  src/js/components/leftPanel/layersPanel/BasemapLayersGroup.tsx
  src/js/components/leftPanel/layersPanel/DateRangeModisViirs.tsx
  src/js/components/leftPanel/layersPanel/DefaultLayerGroup.tsx
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/leftPanel/layersPanel/ImageryLayersGroup.tsx
  src/js/components/leftPanel/layersPanel/LayerToggleSwitch.tsx
  src/js/components/leftPanel/layersPanel/LayerTransparencySlider.tsx
  src/js/components/leftPanel/layersPanel/LayerVersionPicker.tsx
  src/js/components/leftPanel/layersPanel/RecentImagery/CloudSlider.tsx
  src/js/components/leftPanel/layersPanel/RecentImagery/DaySelector.tsx
  src/js/components/leftPanel/layersPanel/RecentImagery/ImageStylePicker.tsx
  src/js/components/leftPanel/layersPanel/RecentImagery/ImagerySlider.tsx
  src/js/components/leftPanel/layersPanel/RecentImagery/MonthSelector.tsx
  src/js/components/leftPanel/layersPanel/RecentImagery/RecentImageryModal.tsx
  src/js/components/leftPanel/layersPanel/RecentImagery/TileThumbnails.tsx
  src/js/components/mapWidgets/widgetContent/CanopyDensityContent.tsx
  src/js/components/mapWidgets/widgetContent/SubscriptionContent.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesForm.tsx
  src/js/components/mapWidgets/widgetContent/penContent.tsx
  src/js/components/report/DatePicker.tsx
  src/js/components/report/ReportChartsComponent.tsx
  src/js/components/report/ReportRangeSlider.tsx
  src/js/components/sharedComponents/CanopyDensityPicker.tsx
  src/js/components/sharedComponents/PrintReportButton.tsx
  src/js/components/sharedComponents/SubscribeButton.tsx
  src/js/components/sharedComponents/TimeSlider.tsx
  src/js/helpers/mapController/miscLayerHelpers.ts
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#1023 Ticket 1015 - left align text
  src/css/leftpanel.scss
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/leftPanel/layersPanel/ImageryLayersGroup.tsx
Labels: 4.x Upgrade

#1020 Ticket 1007 - subscription alerts
  configs/subscribeToAlerts.translations.ts
  src/js/components/leftPanel/dataPanel/subscribeToAlerts/AlertCarousel.tsx
  src/js/components/leftPanel/dataPanel/subscribeToAlerts/NameYourSubscription.tsx
  src/js/components/leftPanel/dataPanel/subscribeToAlerts/SubscribeToAlerts.tsx
  src/js/components/leftPanel/dataPanel/subscribeToAlerts/SubscriptionSaved.tsx
  src/js/components/modal/modalCard.tsx
  src/js/components/sharedComponents/SubscribeButton.tsx
Labels: 4.x Upgrade

#1025 bug fix when we are in share mode and we launch report flow, now with
  src/js/components/sharedComponents/PrintReportButton.tsx
Labels: 4.x Upgrade, bug

#1026 991 "Solid" type legend Implementation
  configs/countryConfigs/cameroon.js
  src/css/legend.scss
  src/js/components/legend/generateLegendItems.tsx
  src/js/helpers/dataPanel/DataPanel.ts
  src/js/helpers/layerScaleCheck.ts
Labels: 4.x Upgrade, bug

#1031 Legend refactor
  docs/README.md
  docs/mapbuilder diagrams.drawio
  src/js/components/legend/generateLegendItems.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/mapController/miscLayerHelpers.ts
Labels: 4.x Upgrade

#1030 Ticket 1024 - Subscribe to alerts flow styling
  src/css/alertCarousel.scss
  src/css/modalCard.scss
  src/js/components/leftPanel/dataPanel/subscribeToAlerts/AlertCarousel.tsx
  src/js/components/leftPanel/dataPanel/subscribeToAlerts/NameYourSubscription.tsx
  src/js/components/leftPanel/dataPanel/subscribeToAlerts/SubscribeToAlerts.tsx
  src/js/components/leftPanel/dataPanel/subscribeToAlerts/SubscriptionSaved.tsx
  src/js/components/modal/modalCard.tsx
Labels: 4.x Upgrade

#1027 Ticket 934 - Layers Info content & logic
  package-lock.json
  package.json
  src/css/leftpanel.scss
  src/css/modalCard.scss
  src/js/components/sharedComponents/InfoContent.tsx
  src/js/helpers/mapController/miscLayerHelpers.ts
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#1032 Ticket 1028 - Loading state for analysis tab
  src/css/leftpanel.scss
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
Labels: 4.x Upgrade

#1043 Geometry precision reduction
  src/js/helpers/dataPanel/DataPanel.ts
Labels: 4.x Upgrade

#1045 Swap vega link to CDN link to be ready for PROD
  src/index.html
  src/library.html
Labels: 4.x Upgrade

#1044 Ticket 1029 - google analytics integration
  src/index.html
  src/js/components/App.tsx
  src/js/store/appSettings/reducers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#1047 Adding line and image support for feature server layers
  src/js/components/legend/generateLegendItems.tsx
Labels: 4.x Upgrade

#1048 Choropleth legend type support
  src/js/components/legend/generateLegendItems.tsx
Labels: 4.x Upgrade

#1050 Better loading state for vega charts in the report component
  src/js/components/report/ReportChartsComponent.tsx
Labels: 4.x Upgrade

#1052 Attribute api formatting for dates, short term solution
  src/js/helpers/dataPanel/DataPanel.ts
  src/js/helpers/dataPanel/formatAttributes.ts
Labels: 4.x Upgrade

#1046 Various Performance improvements
  src/js/components/App.tsx
  src/js/components/leftPanel/layersPanel/DefaultLayerGroup.tsx
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/leftPanel/layersPanel/ImageryLayersGroup.tsx
  src/js/components/leftPanel/layersPanel/LayersTabView.tsx
  src/js/components/leftPanel/layersPanel/WebmapLayersGroup.tsx
  src/js/components/modal/modalCard.tsx
Labels: 4.x Upgrade

#1056 Ticket 954 - Translations audit
  configs/leftPanel.translations.ts
  configs/modal.config.ts
  src/css/leftpanel.scss
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/leftPanel/dataPanel/DefaultTabView.tsx
  src/js/components/leftPanel/layersPanel/GenericLayerControl.tsx
  src/js/components/mapWidgets/widgetContent/CanopyDensityContent.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesDDSection.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesDMSSection.tsx
  src/js/components/mapWidgets/widgetContent/coordinatesForm.tsx
  src/js/components/mapWidgets/widgetContent/shareContent.tsx
  src/js/components/report/ReportChartsComponent.tsx
  src/js/components/sharedComponents/CanopyDensityPicker.tsx
  src/js/components/sharedComponents/InfoContent.tsx
Labels: 4.x Upgrade

#1057 Refactor mouse location tracking when user edits drawn/uploaded shape on
  src/js/components/MapContent.tsx
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/mapWidgets/userPointPopup.tsx
  src/js/controllers/mapController.ts
Labels: 4.x Upgrade

#1054 Ticket 880 - draw message
  src/css/popup.scss
  src/js/components/MapContent.tsx
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/mapWidgets/userPointPopup.tsx
  src/js/controllers/mapController.ts
  src/js/store/appState/actions.ts
  src/js/store/appState/reducers.ts
  src/js/store/appState/types.ts
  src/js/store/mapview/actions.ts
  src/js/store/mapview/reducers.ts
  src/js/store/mapview/types.ts
Labels: 4.x Upgrade

#1055 Multi Poly Fix
  src/js/components/Report.tsx
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/leftPanel/dataPanel/DataTabView.tsx
  src/js/components/report/ReportUtils.ts
  src/js/components/sharedComponents/UploadFile.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/MapGraphics.ts
Labels: 4.x Upgrade

#1058 Print Modal respects custom color theme for buttons
  src/js/components/mapWidgets/widgetContent/printContent.tsx
Labels: 4.x Upgrade

#1059 913 legend hide by config (Default)
  src/js/components/LegendPanel/LegendPanel.js
  src/resources.js
Labels: WCS

#916 WCS - Default webmap transparency fix
  .eslintrc
  configs/vibrant_oceans.js
  src/js/components/Map.js
  src/resources.js
Labels: WCS

#1060 WCS cloudfunctions
  configs/temp_cloudfns.js
  src/js/components/AnalysisPanel/Analysis.js
Labels: WCS

#1062 Ticket 1035 - lighthouse accessibility score
  src/index.html
  src/js/components/header/LanguageDropdown.tsx
  src/js/components/header/ThemeDropdown.tsx
  src/js/components/leftPanel/LeftPanel.tsx
  src/js/components/mapWidgets/hideWidget.tsx
  src/js/components/mapWidgets/measureWidget.tsx
  src/js/components/mapWidgets/penWidget.tsx
  src/js/components/mapWidgets/printWidget.tsx
  src/js/components/mapWidgets/refreshWidget.tsx
  src/js/components/mapWidgets/searchWidget.tsx
  src/js/components/mapWidgets/shareWidget.tsx
  src/js/components/mapWidgets/zoomWidget.tsx
Labels: 4.x Upgrade

#1063 WCS -4x Alignment Part 1
  configs/countryConfigs/natures_strongholds.js
  configs/countryConfigs/temp_cloudfns.js
  configs/countryConfigs/vibrant_oceans.js
  src/css/leftpanel.scss
  src/css/legend.scss
  src/css/report.scss
  src/js/components/Report.tsx
  src/js/components/header/Header.tsx
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/leftPanel/analysisPanel/VegaChartContainer.tsx
  src/js/components/leftPanel/analysisPanel/VegaChartCreator.tsx
  src/js/components/leftPanel/layersPanel/WebmapLayersGroup.tsx
  src/js/components/legend/Legend.tsx
  src/js/components/legend/generateLegendItems.tsx
  src/js/components/report/ReportChartsComponent.tsx
  src/js/controllers/mapController.ts
  src/js/helpers/dataPanel/DataPanel.ts
  src/js/helpers/mapController/configParsing.ts
  src/js/helpers/mapController/miscLayerHelpers.ts
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade, WCS

#1067 Legend not updating with lang change fix
  src/js/components/legend/generateLegendItems.tsx
Labels: 4.x Upgrade

#1068 WCS 4x Alignment Part 2 - WIP
  configs/countryConfigs/natures_strongholds.js
  configs/countryConfigs/vibrant_oceans.js
  src/css/leftpanel.scss
  src/js/components/Report.tsx
  src/js/components/leftPanel/analysisPanel/BaseAnalysis.tsx
  src/js/components/leftPanel/analysisPanel/VegaChartContainer.tsx
  src/js/components/leftPanel/analysisPanel/VegaChartCreator.tsx
  src/js/components/leftPanel/analysisPanel/analysisUtils.ts
  src/js/components/leftPanel/analysisPanel/fragmentationVegaSpec.ts
  src/js/components/legend/generateLegendItems.tsx
  src/js/components/report/ReportChartsComponent.tsx
  src/js/store/appSettings/types.ts
Labels: 4.x Upgrade

#1066 WCS Layer visibility bug fix
  src/js/components/LegendPanel/LegendPanel.js
  src/js/helpers/LayersHelper.js
Labels: WCS

#1074 Ticket 1070 - mobile header styling
  src/css/header.scss
  src/css/variables.scss
Labels: 4.x Upgrade

#1075 Ticket 1071 - more mobile button
  src/css/leftpanel.scss
  src/images/hamburgerIcon.svg
  src/js/components/leftPanel/LeftPanel.tsx
  src/js/components/leftPanel/MenuTabView.tsx
  src/js/components/leftPanel/TabViewContainer.tsx
  src/js/components/mapWidgets/widgetContent/myGFWContent.tsx
Labels: 4.x Upgrade
